schema_version = "1.0.0"

id = "kinefig"
version = "0.0.1"
name = "KineFig"
tagline = "Articulated figure tools for Blender"
maintainer = "gndme"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
